"""Single gateway for robot motion commands and run-time safety limits."""

from __future__ import annotations

import time
from typing import Sequence

import numpy as np

from app.config import SafetyConfig
from robot.base import RobotInterface


class SafetyViolation(RuntimeError):
    """Raised when a requested robot command violates configured safeguards."""


class SafetyManager:
    """Apply speed, camera, timeout, and commanded-travel safety checks."""

    def __init__(self, robot: RobotInterface, config: SafetyConfig) -> None:
        self.robot = robot
        self.config = config
        self._align_started_at: float | None = None
        self._cumulative_travel_mm = 0.0
        self._last_velocity_time: float | None = None
        self._last_velocity_mm_s = np.zeros(2, dtype=np.float64)
        self._camera_failures = 0

    def begin_alignment(self) -> None:
        self._align_started_at = time.monotonic()
        self._cumulative_travel_mm = 0.0
        self._last_velocity_time = time.monotonic()
        self._last_velocity_mm_s[:] = 0.0
        self._camera_failures = 0

    def alignment_elapsed_s(self) -> float:
        return 0.0 if self._align_started_at is None else time.monotonic() - self._align_started_at

    def report_camera_frame(self, frame_ok: bool) -> None:
        self._camera_failures = 0 if frame_ok else self._camera_failures + 1
        if self._camera_failures >= self.config.camera_failure_limit:
            self.stop_all()
            raise SafetyViolation(f"Camera failed for {self._camera_failures} consecutive frames")

    def move_to_observe_pose(self) -> None:
        self.robot.move_to_observe_pose()
        self.robot.wait_until_stop()

    def move_pose_linear(self, pose: Sequence[float]) -> None:
        """以受控笛卡尔直线到达已确认的绝对位姿。"""
        self.stop_xy()
        self.robot.move_pose_linear(pose)
        self.robot.wait_until_stop()

    def move_xy_relative(
        self,
        dx_mm: float,
        dy_mm: float,
        max_increment_mm: float | None = None,
    ) -> None:
        """执行一次受限的相对 XY 规划运动。

        ``max_increment_mm`` 可为特殊的单次相对移动设置更严格的上限。
        如果当前处于一次 IBVS 对准中，该位移会计入本轮累计指令行程，避免
        多次视觉移动的合计距离绕过 ``max_xy_travel_mm``。
        """
        increment = np.array([dx_mm, dy_mm], dtype=np.float64)
        if not np.all(np.isfinite(increment)):
            raise SafetyViolation("Requested relative XY increment contains NaN or infinity")
        increment_norm = float(np.linalg.norm(increment))
        limit = self.config.max_xy_travel_mm
        if max_increment_mm is not None:
            if not np.isfinite(max_increment_mm) or max_increment_mm <= 0:
                raise SafetyViolation("Relative XY increment limit must be positive and finite")
            limit = min(limit, float(max_increment_mm))
        if increment_norm > limit:
            raise SafetyViolation(
                f"Requested relative XY increment {increment_norm:.3f} mm exceeds {limit:.3f} mm limit"
            )
        self.stop_xy()
        combined_travel = self._cumulative_travel_mm + increment_norm
        if self._align_started_at is not None and combined_travel > self.config.max_xy_travel_mm:
            raise SafetyViolation("Visual alignment exceeds configured travel limit")
        self.robot.move_xy_relative(dx_mm, dy_mm)
        self.robot.wait_until_stop()
        if self._align_started_at is not None:
            self._cumulative_travel_mm = combined_travel

    def set_xy_velocity(self, velocity_mm_s: np.ndarray) -> None:
        """Clamp the command and track the integrated, commanded XY travel."""
        velocity = np.asarray(velocity_mm_s, dtype=np.float64)
        if velocity.shape != (2,):
            raise SafetyViolation("XY velocity must have exactly two components")
        if not np.all(np.isfinite(velocity)):
            raise SafetyViolation("XY velocity contains NaN or infinity")
        now = time.monotonic()
        self._integrate_previous_velocity(now)
        if self._cumulative_travel_mm > self.config.max_xy_travel_mm:
            self.stop_xy()
            raise SafetyViolation("Maximum commanded XY travel exceeded")
        self.robot.set_xy_velocity(float(velocity[0]), float(velocity[1]))
        self._last_velocity_mm_s = velocity.copy()

    def stop_xy(self) -> None:
        now = time.monotonic()
        self._integrate_previous_velocity(now)
        try:
            self.robot.stop_xy()
        finally:
            self._last_velocity_mm_s[:] = 0.0
            self._last_velocity_time = now

    def _integrate_previous_velocity(self, now: float) -> None:
        """Accumulate scalar path length generated by the command active since the last call."""
        if self._last_velocity_time is not None and self._align_started_at is not None:
            elapsed_s = max(0.0, now - self._last_velocity_time)
            self._cumulative_travel_mm += float(np.linalg.norm(self._last_velocity_mm_s)) * elapsed_s
        self._last_velocity_time = now

    def move_z_absolute(self, z_mm: float, speed_mm_s: float) -> None:
        self.stop_xy()
        self.robot.move_z_absolute(z_mm, speed_mm_s)
        self.robot.wait_until_stop()

    def move_z_relative(self, dz_mm: float, speed_mm_s: float) -> None:
        self.stop_xy()
        self.robot.move_z_relative(dz_mm, speed_mm_s)
        self.robot.wait_until_stop()

    def stop_all(self) -> None:
        now = time.monotonic()
        self._integrate_previous_velocity(now)
        try:
            self.robot.stop_all()
        finally:
            self._last_velocity_mm_s[:] = 0.0
            self._last_velocity_time = now
